### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by SmallMunich** [dtczhl/dtc-pointpillars-keras#1]
Hi, @dtczhl . can you write readme.txt for tell us how to use it ?

thanks.

**Comment by dtczhl** [comment]
> Hi, @dtczhl . can you write readme.txt for tell us how to use it ?
> 
> thanks.

Hi, it is unfinished. I don't have time to continue it. Please try search for other people's GitHub.

**Comment by SmallMunich** [comment]
> > Hi, @dtczhl . can you write readme.txt for tell us how to use it ?
> > thanks.
> 
> Hi, it is unfinished. I don't have time to continue it. Please try search for other people's GitHub.

ok, thanks for your reply.
